server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
  #  driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      port: 27017
      database: spring-shen
      host: localhost
      uri: mongodb://localhost:27017




## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/freewind/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.freewind.entity # 注意：对应实体类的路径
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#eureka 客户端
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      
      
env: dev     
